# Generated by Django 4.0.1 on 2022-01-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
