# Generated by Django 4.0.1 on 2022-01-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_url_category_slug_rename_url_genre_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='slug',
            new_name='url',
        ),
    ]
